services:
  node:
    build: .
    container_name: ery-ai
    expose:
      - ${PORT}
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
      - API_REQUEST=${API_REQUEST}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_ASSISTANT_NAME=${OPENAI_ASSISTANT_NAME}
      - OPENAI_CREATE_ASSISTANT=${OPENAI_CREATE_ASSISTANT}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "3000:80"
    volumes:
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
